<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7HDVN5M" failures="1" tests="2" name="Test" time="19.006" errors="0" timestamp="2022-08-26T18:46:42 IST">
  <testcase classname="qa.tests.LoginPageTest" name="validateLoginTest" time="4.741">
    <failure type="java.lang.AssertionError" message="Test is failed expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList]">
      <![CDATA[java.lang.AssertionError: Test is failed expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList]
at qa.tests.LoginPageTest.validateLoginTest(LoginPageTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateLoginTest -->
  <testcase classname="qa.tests.LoginPageTest" name="validateLogoTest" time="0.703"/>
</testsuite> <!-- Test -->
